### ISSUE TITLE
Isomorphic (universal) React?

### ISSUE THREAD

**Issue by JonathanWi** [dnieh/react-planks#1]
Hey!

Thanks for your awesome component, but it doesn't seem to work with server-sider react, is it the expected behavior?

What's weird is that  the width is computed but not the position (no absolute position on the .plank class)

Any help would be greatly appreciated :)

**Comment by dnieh** [comment]
Hey thanks for the question. I didn't write this to work with server side react. That's definitely something I want to do for the future. 

Also in regards to the width issue, this is a bug that I haven't pushed out a fix yet for. Basically the css needs to be defined as follows (or you can set this as an inline react style):

``` css
.planks-container {
  position: relative;
}

.plank {
  visibility: hidden;
  position: absolute;
}
```

Hope this helps! I'll be rolling out more updates soon as this is in active development.
